version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: harmonicsound_homolog
      MYSQL_USER: app
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

    nginx:
      image: nginx:latest
      container_name: nginx-container
      ports:
        - "8080:80"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      depends_on:
        - mysql
      networks:
        - app-network

    Backend:
      build: 
        context: ./backend
        dockerfile: Dockerfile
      container_name: backend-container
      ports:
        - "3000"
      depends_on:
        - mysql
      networks:
        - app-network
      
  volumes:
    mysql-data:

    networks:
      - app-network:
        